name: Upload to PyPi

on:
  release:
    types: [created]
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [ '3.8', '3.9', '3.10', '3.11']
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build

      - name: Archive wheel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist/*.whl

      - name: Archive tar.gz artifacts
        uses: actions/upload-artifact@v3

        if: ${{ matrix.python-version == '3.11' }} 
        with:
          name: dist-without-markdown
          path: |
            dist/*.tar.gz

  publish:
    name: Publish to Pypi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist
        
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist

      # - name: Publish package
      #   uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_SIMSTRING_UPLOAD_TOKEN }}


